const Discord = require('discord.js');
require('dotenv').config();
/**@type bigint */
const perms = BigInt(process.env.PERMS);
const autoRolesChannel = process.env.AUTO_ROLES_CHANNEL;
const adminRole = process.env.ADMIN_ROLE;

function randomColor(brightness){
    function randomChannel(brightness){
        var r = 255-brightness;
        var n = 0|((Math.random() * r) + brightness);
        var s = n.toString(16);
        return (s.length==1) ? '0'+s : s;
    }
    return '#' + randomChannel(brightness) + randomChannel(brightness) + randomChannel(brightness);
}

module.exports = {
    name: "add-role",
    /** @type Discord.ApplicationCommandData */
    commandData: {
        name: "add-role",
        description: "Añade un nuevo rol a los autoroles",
        defaultPermission: true,
        options: [
            {
                name: "nombre",
                type: 'STRING',
                description: "nombre del nuevo rol",
                required: true
            },
            {
                name: "emoji",
                description: "emoji del nuevo rol",
                type: "STRING",
                required: true
            }
        ]
    },
    /** @param {Discord.CommandInteraction} interaction*/
    async commandRun(interaction){
        if (!interaction.member.roles.cache.has(adminRole)) return interaction.reply("Accesso Denegado");
        await interaction.defer();
        /** @type Discord.TextChannel */
        const channel = interaction.guild.channels.cache.get(autoRolesChannel);
        const webhook = (await channel.fetchWebhooks()).first();

        let emoji = interaction.options.get("emoji").value;
        let nombre = interaction.options.get("nombre").value;
        
        let role;
        //CREAR ROL
        await interaction.guild.roles.create({
            name: nombre,
            permissions: perms,
            mentionable: true,
            hoist: true,
            color: randomColor(30)
        }).then((result) =>{
            role = result;
        })
        
        let fieldName = `${emoji}➜${nombre}`
        let fieldValue = `<@&${role.id}>`

        interaction.editReply(`${emoji}➜${nombre}\n<@&${role.id}>`)
        try{
            let msg = (await channel.messages.fetch({limit:1})).first();
            if (msg.embeds.length == 1){
                let embed = msg.embeds[0];
                if (embed.fields.length<20){
                    console.log("Reuse");
                    let hook = await msg.fetchWebhook()
                    hook.editMessage(msg.id,{
                        embeds: [embed.addField(fieldName,fieldValue,true).setFooter("Generated by DovuxModsBOT","https://cdn.discordapp.com/icons/738674787332784169/86ddd16c139e4b70d61e2f085f82daf9.png")],
                    }).then(
                        interaction.editReply("Success")
                    )
                    return;
        }}
        }catch (err){
            console.log(err);
        }
        let embed = new Discord.MessageEmbed().addField(fieldName,fieldValue,true).setColor("#ff00ff").setFooter("Generated By DovuxModsBOT","https://cdn.discordapp.com/icons/738674787332784169/86ddd16c139e4b70d61e2f085f82daf9.png");
        webhook.send({
            embeds: [embed]
        });
        console.log("NEW")
        
    }
}